version: '3'
services:
  pigx-ui:
    build:
      context: .
    restart: always
    container_name: pigx-ui
    image: pigx-ui
    networks:
      - pigx_default
    external_links:
      - pigx-gateway
    ports:
      - 80:80

# 加入到后端网络， 默认为 pigx_default  | docker network ls   查看
networks:
  pigx_default:
    external: true